config/routes.rb
B5::Application.routes.draw do

  scope :module => "organize" do

    resources :queue_items_cart,  :only => [:show,:update],  :controller => 'queue_items_cart' do

      member do
        post :assign
        post :cart
        post :order
        post :run
        post :redo
        post :list
        post :update
      end
    end

    resources :queue_items do
      collection do
        get :packages
        get :results
        get :new_task
        get :work
        get :upload
        post :upload
      end
      member do
        get :is_reason_required
      end


    end
  end

  resources :outline_queues do
    resource :experiment_order_wizard, only: [] do
      collection do
        get :step1_new
        post :step1_create
      end
    end
  end

  resources :experiment_items, only: [:update, :destroy]

  resources :experiment_consolidation_wizards, :only => [] do
    collection do
    end
    member do
      get :step1
      put :step1_save

      get :step2

      get :step3_create
      get :step3_edit
      post :step3_reset
      post :step3_update

      get :step4_new
      get :step4_preview
      put :step4_create
      post :step4_create
      put :finalize
      post :finalize

      get :step5
    end
  end

  resources :experiment_order_wizards, only: [] do
    collection do
      get :abandon
    end
    member do
      put :step1_update
      get :step1_edit
      get :step2
      get :step3
      get :step4
      post :confirm
      get :abandon
    end
  end



  resources :task_output_files, :only => [:new, :show, :create] do
    member do
      put :create
      post :create
      get :renew_form
      get :preview
    end
  end

  resources :output_file_templates do
    collection do
      get :help
    end
  end

  resources :rl_results do
    member do
      get :result
    end
    collection do
      get :pivot
    end
  end

  resources :dilution_maps do
    collection do
      post :renew_form
      post :build_wells
      put :renew_form
      put :build_wells
    end
  end


  resources :task_barcodes, :except => [:update, :edit] do
    collection do
      get :show_collection
    end

  end

  resources :cdb_samples, :controller => 'rl_sample'

  resources :rl_samples do
    member do
      get :sample

      resource :query, :controller => 'rl_sample_query' do
        collection do
          post :add_columns
          get :update_options
        end
      end
    end

  end

  resources :cdb_methods, :controller => 'rl_method'

  resources :rl_methods do
    member do
      get :method
    end
  end

  resources :process_version_file_templates

  scope :module => "organize" do


    resources :queue_items do
      collection do
        get :packages
        get :results
        get :new_task
        get :work
        get :upload
        post :upload

        resources :carts, :as => 'queue_carts', :controller => 'queue_item_carts' do
          member do
            get :new_task
            post :run
            get :renew_form
          end
        end

      end
    end


    resources :outline_queues do
      member do
        get :orders
      end
    end

  end

  resources :tasks do

    resources :task_barcodes, :only => [:index]

    resources :dilution_slots,
              :only => [:new] do
      collection do
        get :show
        put :create
        post :update
      end
    end

    collection do
      get :results
      post :refresh # extra call to allow for form refresh
    end
    member do
      get :sheet
      get :copy
      get :update_preview_and_show
      post :select
      post :assign_member_to
      get :assign
      post :assign
      get :update_row
      get :print
      get :flexible
      get :update_queue
      get :clear
      get :remove
      post :remove
      get :results
      get :notify
      get :close
      get :fill
      get :recalc
    end
  end

  #TODO: this is just a subclass of Task. We should be re-using the Task routes
  resources :experiments, :controller => 'tasks' do
    resources :task_barcodes, :only => [:index]
    collection do
      get :results
      post :refresh # extra call to allow for form refresh
    end
    member do
      get :sheet
      get :copy
      get :update_preview_and_show
      get :select
      post :select
      get :assign
      post :assign
      get :update_row
      get :print
      get :flexible
      get :update_queue
      get :clear
      get :remove
      post :assign_member_to
      post :remove
      get :results
      get :notify
      get :close
      get :fill
      get :recalc
    end
  end

end

app/controllers/organize/queue_items_cart_controller.rb
class Organize::QueueItemsCartController < ApplicationController

  use_authorization Role::MODULE_QUEUE,
                    Role::RIGHT_USE => [:show],
                    Role::RIGHT_BUILD => [:cart, :assign, :run, :redo, :list, :create]


  before_filter :verify_folder_is_changeable, :only => [:run]

  #
  # Show Query with new start users cart of for this query
  #
  def show
    setup_query
    @selected_list = @cart.get_items
  end

  #
  # Show cart to update of properties
  #
  def cart
    setup_items
  end

  #
  # assign items to new experiment
  #
  def assign
    setup_items
  end

  #
  # post, modify items in cart
  #
  def update
    setup_items
    if @cart.cart_items.size ==0
      flash[:warning] = 'No items updated'
      redirect_to(params[:back_url] ||home_url)
    elsif params['submit_assign']
      reassign_items(params[:queue_item])
    elsif params['submit_update']
      update_items(params[:queue_item])
    end
  end

  protected


  def update_items(row)
    row[:status_summary] ='bulk update from cart'
    row.map { |name, value| row.delete(name) if value.blank? }
    if State.where('id=? and level_no < 2', row[:state_id]).exists?
      @cart.list.each { |queue_item| queue_item.clear_task_and_update(row) }
      flash[:success] = "Update #{@cart.list.size} Items and removed from experiments"
    else
      @cart.update_action(row)
      flash[:success] ="Updated #{@cart.list.size} Items"
    end
    return redirect_to(params[:back_url] ||home_url)
  end


  def reassign_items(row)
    logger.info "reassign_items to #{row.inspect}"
    if row[:task_id].blank?
      row[:status_summary] ='bulk removed experiment from cart'
      @cart.list.each { |queue_item| queue_item.clear_task_and_update(row) }
      flash[:success] ="Updated #{@cart.list.size} Items"
    else
      task = Task.find(row[:task_id])
      if task.changeable?
        task.sheet.populate_from_queue( @cart.list )
        flash[:success] ="Updated #{@cart.list.size} Items"
      else
        flash[:warning] ='New experiment is not changeable'
      end
    end
    return redirect_to(params[:back_url] ||home_url)
  end


  #
  # Find existing cart and get outline_queue
  #
  def setup_cart
    @cart = Cart.new
    @cart.query = @query
    @cart.model = QueueItem
    @cart.reference = @outline_queue
    @cart
    @cart.set_items(params[:items]) unless params[:items].blank?
  end

  def setup_query
    @outline_queue = OutlineQueue.find(params[:id])
    @project_folder = @outline_queue.project_element
    @query = QueryEngine.query('queue_items.index', :outline_queue => @outline_queue)
    @query_manager = QueryEngine::QueryGrid.new(@query)
    setup_cart
  end

  def setup_items
    setup_query
    @queue_item = QueueItem.new(params[:queue_item])
    @list = ::List.new(params[:list])
    @user_request = Request.new(params[:user_request])
    @result_task = ResultTask.new(params[:result_task])
  end

end

app/controllers/organize/queue_items_controller.rb
# == Queue Item Controller
# This is used to display a queue item and allows the user to delete it
#
#
# == Actions
#
# * index        all queue items global query
# * list         list all items for given outline
# * new/create   create a new item
# * edit/update  edit a exiting item
# * destroy      destroy item and all its dependent objects
#
# == Notice
#
# Copyright © 2006 Robert Shell, Alces Ltd All Rights Reserved
# See license agreement for additional rights
#
class Organize::QueueItemsController < ApplicationController
  unloadable
  use_authorization Role::MODULE_QUEUE,
                    Role::RIGHT_USE => [:index,:show, :status, :results, :items],
                    Role::RIGHT_BUILD => [:new, :edit, :update, :destroy, :update_item, :upload,
                                          :new_task, :remove_cart, :add_cart, :update_cart, :clear_cart]

  before_filter :find_queue, :only => [:index, :results, :work, :show_cart, :remove_cart,
                                       :add_cart, :update_cart, :clear_cart, :upload]
  before_filter :find_item, :only => [:show, :is_reason_required, :destroy]
  before_filter :verify_folder_is_changeable, :only => [:update_cart, :run, :edit, :upload]

  helper Organize::OutlineQueuesHelper
  #
  # Report on all queue items
  #
  # All QueueItemContext records
  #
  def index
    if params[:outline_queue_id]
      @outline_queue = OutlineQueue.find(params[:outline_queue_id])
      @project_folder = @outline_queue.folder
      @query = QueryEngine.query('queue_items.index', :outline_queue => @outline_queue)
      respond_to do |format|
        format.html { render :action => 'cart_list' }
      end
    else
      @query = QueryEngine.query('queue_items.index')
    end
  end

  #
  # Report on all work packages in system
  #
  # All work packages in the system
  #
  def packages
    @query = QueryEngine.query('queue_items.packages')
    respond_to do |format|
      format.html { render :action => 'index' }
    end
  end

  def results
    subject = :organization
    name = @outline_queue.dom_id(:results)
    @query = QueryEngine.query('queue_items.packages', :outline_queue => @outline_queue)
    @title = t('queue_items.results.title')

    respond_to do |format|
      format.html { render :action => 'index' }
    end
  end

  def show
    @outline_queue = @queue_item.queue
    @user_request = @queue_item.request
  end

  def destroy
    @queue_item.destroy
    redirect_to :action => 'index'
  end

  def is_reason_required
    respond_to do |format|
    format.json{render :json=>{:required => @queue_item.requires_reason_for_change_to(params[:state])}}
      end
  end

  protected

  def find_item
    if params[:id] == 'carts'
      flash[:warning] = t('organize.queue_items.non_selected')
    end
    @queue_item =QueueItem.find(params[:id])
  rescue Exception => ex
    logger.warn flash[:warning]= "Exception in #{self.class}: #{ex.message}"
    return show_access_denied
  end

  def find_queue
    if params[:project_element_id]
      @project_folder = ProjectElement.load(params[:project_element_id])
      @outline_queue = @project_folder.reference
    else
      @outline_queue = OutlineQueue.find(params[:outline_queue_id])
      @project_folder = @outline_queue.folder
    end

    unless @outline_queue && @outline_queue.is_a?(OutlineQueue)
      return show_access_denied
    end

    set_project_folder(@project_folder)
  rescue Exception => ex
    logger.warn flash[:warning]= "Exception in #{self.class}: #{ex.message}"
    return show_access_denied
  end

end

app/helpers/organize/queue_items_cart_helper.rb
module Organize::QueueItemsCartHelper

  def selector_for_item(queue_item,idx)
    if queue_item.can_plan?
      check_box_tag "items[#{idx}]",queue_item.id ,true
    elsif queue_item.state.level_no < 1
      check_box_tag("items[#{idx}]",queue_item.id ,false)
    elsif queue_item.state.level_no > 2
       "#{check_box_tag("items[#{idx}]",queue_item.id ,false, :disabled => true)} Finalized".html_safe
    end
  end

end

app/helpers/organize/queue_items_helper.rb
module Organize::QueueItemsHelper

  def new_task_button_message
    if current_project_folder.changeable? and right?(Role::MODULE_QUEUE, Role::RIGHT_BUILD)
      ""
    elsif current_project_folder.changeable?
      t('queue_items.queue_items_in_cart.no_rights')
    else
      t('queue_items.queue_items_in_cart.not_changeable', :element => @outline_queue.element_type.name)
    end
  end




end

app/views/organize/queue_items/_item_cdb.html.erb
<div class="portlet">
  <div style="max-height:250px; overflow:auto">

    <% @sample = @queue_item.object %>
    <% if @sample and @sample.is_a?(CdbSample) %>
      <h2><%= t('.title', :sample => @sample.name) %></h2>

      <img src='<%= SystemSetting.sample_image_renderer_url ? "#{SystemSetting.sample_image_renderer_url}#{@sample.sample_id}".html_safe : "#" %>'/>

      <dl class="dl-horizontal">
        <% [
             :sample_id, :sample_code, :saltcode, :sample_batch, :chemical_name,
             :chemist, :comment_z, :date_of_submission, :lab_sample_id,
             :mol_weight_sample, :mol_weight_sample, :mol_formula_sample, :project
           ].each do |attribute| %>
          <dt><%= CdbSample.human_attribute_name attribute %></dt>
          <dd><%= @sample.send(attribute) %></dd>
        <% end %>

        <% phys_chem = @sample.phys_chem_props[0] %>
        <dt><%= RlSamplePhysChemProp.human_attribute_name(:purity) %></dt>
        <dd><%= phys_chem.purity if phys_chem %></dd>
      </dl>
    <% end %>
  </div>
</div>

app/views/organize/queue_items/_item_details.html.erb
<div class="portlet">
  <dl class='dl-horizontal'>
    <dt><%= @outline_queue.element_type.name %></dt>
    <dd><%= link_to "#{ @outline_queue.name}", outline_queue_path(:id => @outline_queue.id) %>
      (<%= @outline_queue.parameter.name %>)
    </dd>

    <dt><%= @user_request.element_type.name %></dt>
    <dd>
      <%= link_to @user_request.name, request_path(:id => @queue_item.request_id) %>
      (<%= t('queue_items.show.requested_by', :member => @user_request.requested_by_member, :due => short_date(@user_request.expected_at)) %>
      )
    </dd>

    <dt><%= t('activerecord.models.state.one') %></dt>
    <dd><%= @user_request.state %></dd>

    <dt><%= t('.request_details') %></dt>
    <dd><%= link_to @queue_item.request_row.label,
                    task_context_path(:id => @queue_item.request_task_context_id) if @queue_item.request_row %></dd>

    <dt><%= t('.run_details') %></dt>
    <dd><%= link_to @queue_item.result_row.label,
                    task_context_path(:id => @queue_item.result_task_context_id) if @queue_item.result_row %></dd>

    <% [:data_type, :data_name, :expected_at, :created_at].each do |column| %>
      <dt><%= QueueItem.human_attribute_name(column) %></dt>
      <dd><%= formatted_string(@queue_item.send(column)) %> &nbsp;</dd>
    <% end %>
  </dl>

</div>

app/views/organize/queue_items/_item_history.html.erb
<div class="portlet">
  <table class='table table-striped table-bordered'>
    <thead>
    <tr>
      <th><%= t('activerecord.attributes.queue_item_history.state') %></th>
      <th><%= t('activerecord.attributes.queue_item_history.author') %></th>
      <th><%= t('activerecord.attributes.queue_item_history.entered_at') %></th>
      <th><%= t('activerecord.attributes.queue_item_history.days_old') %></th>
      <th><%= t('activerecord.attributes.queue_item_history.reason') %></th>
      <th><%= t('activerecord.attributes.queue_item_history.comment') %></th>
    </tr>
    </thead>
    <tbody>
    <% @queue_item.queue_item_histories.each do |history| %>
        <tr>
          <td>
            <%= history.state_name %>
          </td>
          <td>
            <%= history.entered_by_user.name %>
          </td>
          <td>
            <%= short_date(history.entered_at) %>
          </td>
          <td>
            <%= history.days_old %>
          </td>
          <td>
            <%= history.reason %>
          </td>
          <td>
            <%= history.comments %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/organize/queue_items/_item_history_modal.html.erb
<%= render :layout => 'shared/modal_form',
           :locals => {
             :id => 'queue_item_history',
             :header => @queue_item.name,
             :object => [],
             :options => {:class => 'wide-modal'}
           } do
  render :partial => 'item_history'
end %>

app/views/organize/queue_items/_item_orders.html.erb
<div class="portlet">

    <h2><%= t('.header', :queue_item => QueueItem.model_name.human) %></h2>

    <% if @queue_item.orders.any? %>
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th><%= Order.human_attribute_name(:created_at) %></th>
            <th><%= Order.human_attribute_name(:name) %></th>
            <th><%= Order.human_attribute_name(:outline_queue_id) %></th>
            <th><%= Order.human_attribute_name(:order_profile_id) %></th>
            <th><%= CoastsOrder.human_attribute_name(:status) %></th>
          </tr>
          </thead>
          <tbody>
          <% @queue_item.orders.each do |order| %>
              <tr>
                <td><%= formatted_string order.created_at %></td>
                <td><%= link_to order.name, order_path(order) %></td>
                <td><%= link_to order.outline_queue_name, outline_queue_path(order.outline_queue) %></td>
                <td><%= link_to order.order_profile_name, order_profile_path(order.order_profile) %></td>
                <td><%= order.status %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
    <% else %>
        <%= t('.no_orders_for_queue_item', :queue_item => QueueItem.model_name.human) %>
    <% end %>

    <h2><%= t('.sample_header', :sample => @queue_item.data_type.constantize.model_name.human) %></h2>
    <% if @queue_item.other_orders.any? %>
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th><%= Order.human_attribute_name(:created_at) %></th>
            <th><%= Order.human_attribute_name(:name) %></th>
            <th><%= Order.human_attribute_name(:outline_queue_id) %></th>
            <th><%= Order.human_attribute_name(:order_profile_id) %></th>
            <th><%= CoastsOrder.human_attribute_name(:status) %></th>
          </tr>
          </thead>
          <tbody>
          <% @queue_item.other_orders.each do |order| %>
              <tr>
                <td><%= formatted_string order.created_at %></td>
                <td><%= link_to order.name, order_path(order) %></td>
                <td><%= link_to order.outline_queue_name, outline_queue_path(order.outline_queue) %></td>
                <td><%= link_to order.order_profile_name, order_profile_path(order.order_profile) %></td>
                <td><%= order.status %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
    <% else %>
        <%= t('no_orders_for_sample', :sample => @queue_item.data_type.constantize.model_name.human) %>
    <% end %>

</div>

app/views/organize/queue_items/_item_others.html.erb
<div class="portlet">
  <div style="max-height:250px; overflow:auto">
    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th><%= t('activerecord.attributes.queue_item.request_id') %></th>
        <th><%= t('activerecord.attributes.queue_item.state_id') %></th>
        <th><%= Outline.model_name.human %></th>
        <th><%= OutlineQueue.model_name.human %></th>
        <th><%= t('.run') %></th>
        <th><%= QueueItem.human_attribute_name(:updated_at) %></th>
      </tr>
      </thead>
      <tbody>

      <% @queue_item.other_items.each do |item| %>
        <tr>
          <%= content_tag(:td, link_to(item.request.name, request_path(item.request_id))) %>
          <%= content_tag(:td, item.state.name) %>
          <%= content_tag(:td, link_to(item.queue.outline.name, outline_path(item.queue.outline_id))) %>
          <%= content_tag(:td, link_to(item.queue.name, outline_queue_path(item.outline_queue_id))) %>
          <%= content_tag(:td, item.result_task_context_id.blank? ? '' : link_to(t('activerecord.attributes.queue_item.result_task_id'), task_path(item.result_row.task_id))) %>
          <%= content_tag(:td, short_date(item.updated_at)) %>
        </tr>
      <% end %>

      </tbody>
    </table>
  </div>
</div>

app/views/organize/queue_items/_item_stocks.html.erb
<div class="portlet">
  <% stock_check = CoastsStockCheck.amount_for_order_profiles(@outline_queue.order_profiles,
                                                              [@queue_item.object.sample_id]) %>
  <% @outline_queue.order_profiles.each do |order_profile| %>
      <h2>
        <%= order_profile.name %>
        <% if order_profile.preferred %>
            (Preferred)
        <% end %>
      </h2>
      <% stock_levels = stock_check[order_profile.id][@queue_item.object.sample_id] %>
      <% if stock_levels and stock_levels.any? %>
          <table class="table table-striped table-hover">
            <thead>
            <tr>
              <th><%= CoastsOpu.model_name.human %></th>
              <th><%= t('.amount') %></th>
              <% if order_profile.subways? %>
                  <th><%= t('.tube_id') %></th>
              <% end %>
            </tr>
            </thead>
            <tbody>
            <% stock_levels.each do |level| %>
                <tr>
                  <td><%= level['opu'] %></td>
                  <td><%= level['amount'] %></td>
                  <% if order_profile.subways? %>
                      <td><%= level['tube_id'] %></td>
                  <% end %>
                </tr>
            <% end %>
            </tbody>
          </table>
      <% else %>
          <%= t('.no_stock_message') %>
      <% end %>
  <% end %>
</div>

app/views/organize/queue_items/_upload_form.html.erb
<% form_tag upload_queue_items_path do %>
  <%= hidden_field_tag :id, @outline_queue.id %>
  <div class="pull-left">
    <%= text_area_tag :content, params[:content], :rows => 20, :cols => 50 %>
  </div>
  <div class="pull-left">
    <%= submit_tag t('.submit'), :style => "width:100px;padding:0.5em" %>
    <br/>
    <%= submit_tag t('.test'), :style => "width:100px;padding:0.5em" %>
  </div>
<% end %>

app/views/organize/queue_items/cart_list.html.erb
<% content_for :messages do %>
  <%= render :partial => '/shared/messages' %>
<% end %>

<%= content_for :breadcrumb do %>
  <%= breadcrumbs(@project_folder.self_and_ancestors).html_safe if defined? @project_folder %>
<% end %>

<%= content_for :title do %>
  <%= @project_folder.element_type %>: <%= @project_folder.name %>  : Items
<% end %>


<%= content_for :local_navigation do %>
  <%= toolbar_menu_actions(@project_folder.reference) %>
<% end %>

<%= content_tag(:div,:id=>@query.dom_id).html_safe %>
<%= query_panel(@query, :cart => queue_carts_path(:outline_queue_id => @outline_queue.id, :query_id => @query.id)) %>

app/views/organize/queue_items/index.html.erb
<% content_for :messages do %>
  <%= render :partial => '/shared/messages' %>
<% end %>

<%= content_for :breadcrumb do %>
  <%= breadcrumbs(@project_folder.self_and_ancestors).html_safe if defined? @project_folder %>
<% end %>

<%= content_for :title do %>
  <%= @project_folder.element_type %>: <%= @project_folder.name %>
<% end %>


<%= content_for :local_navigation do %>
  <%= toolbar_menu_actions(@project_folder.reference) %>
<% end %>


<%= render :partial => '/shared/report_panel' %>

app/views/organize/queue_items/show.html.erb
<% content_for :messages do -%>
    <%= render :partial => 'shared/messages', :locals => {:objects => ['queue_item']} %>
<% end %>

<%= content_for :title do %>
    <%= t('activerecord.models.queue_item') %>:
    <%= @queue_item.name %>
<% end %>

<%= content_for :breadcrumb do %>
    <%= breadcrumbs(@queue_item.queue.project_element.self_and_ancestors).html_safe %>
<% end %>

<div class="tab_form">
  <ul class="nav nav-tabs" id="myTab">
    <li class="active"><a href="#history" data-toggle="tab"><%= t('.history') %></a></li>
    <li><a href="#details" data-toggle="tab"><%= t('.details') %></a></li>

    <li><a href="#cdb" data-toggle="tab"><%= t('.cdb') %></a></li>
    <li><a href="#stocks" data-toggle="tab"><%= t('.stocks') %></a></li>
    <li><a href="#orders" data-toggle="tab"><%= t('.orders') %></a></li>
    <li><a href="#others" data-toggle="tab"><%= t('.others') %></a></li>
  </ul>
  <div class="tab-content biorails_form_wrapper">
    <div class="tab-pane active" id="history">
      <%= render :partial => 'item_history' %>
    </div>
    <div class="tab-pane" id="details">
      <%= render :partial => 'item_details' %>
    </div>
    <div class="tab-pane" id="cdb">
      <%= render :partial => 'item_cdb' if @outline_queue.orderable? %>
    </div>
    <div class="tab-pane" id="stocks">
      <%= render :partial => 'item_stocks' if @outline_queue.orderable? %>
    </div>
    <div class="tab-pane" id="orders">
      <%= render :partial => 'item_orders' if @outline_queue.orderable? %>
    </div>
    <div class="tab-pane" id="others">
      <%= render :partial => 'item_others' if @queue_item.other_items.size>0 %>
    </div>
  </div>
</div>

<% content_for :footer do %>
    <%= render :partial => 'shared/audit', :locals => {:item => @queue_item} %>
<% end %>

app/views/organize/queue_items/show.js.erb
<%= handle_open_modal_js do %>
<%= escape_javascript(render :layout => 'shared/modal_form',
           :partial => 'item_history',
           :locals=>{:id=>'orderModal',
             :header => @queue_item.name,
             :object=>[],
             :options=>{:class=>'wide-modal'}
           }) %>
<% end %>

app/views/organize/queue_items/upload.html.erb
<%= render :partial => 'shared/folder_header', :locals => {:folder => @outline_queue.folder, :title => t('.header')} %>

<% content_for :messages do -%>
    <%= render :partial => 'shared/messages', :locals => {:objects => ['queue_item']} %>
<% end %>

<div class='display-form'>
  <%= t('.list_prompt') %>
</div>

<div>
  <div class="pull-left">
    <%= render :partial => 'upload_form' %>
  </div>

  <div class="pull-left">
    <% if @queue_items %>
        <h3 style='margin-top:0'><%= t('.search_results', :no_of_items=>@queue_items.size ) %></h3>
        <%= render :partial => 'queue_items', :locals => {:show_actions => false, :queue_items => @queue_items} %>
    <% end %>

    <% if @queue_items_for_data_names_not_found && @queue_items_for_data_names_not_found.size > 0 %>
        <h3><%= t('.search_results', :no_of_items=>@queue_items_for_data_names_not_found.size ) %></h3>

        <div style="padding-left:1em">
          <%= t('.not_found') %>
          <%= t('.match', :match_items=>@data_names_not_found.collect { |i| "'#{i}'" }.join(', ')) %>
        </div>
        <%= render :partial => 'organize/shared/queue_items', :locals => {:show_actions => false,
                                                                          :items => @queue_items_for_data_names_not_found} %>
    <% end %>
    <br style="clear:both"/>
  </div>
</div>