config/routes.rb
B5::Application.routes.draw do

  scope :module => "organize" do

    resources :queue_items_cart,  :only => [:show,:update],  :controller => 'queue_items_cart' do

      member do
        post :assign
        post :cart
        post :order
        post :run
        post :redo
        post :list
        post :update
      end
    end

    resources :queue_items do
      collection do
        get :packages
        get :results
        get :new_task
        get :work
        get :upload
        post :upload
      end
      member do
        get :is_reason_required
      end


    end
  end

  resources :outline_queues do
    resource :experiment_order_wizard, only: [] do
      collection do
        get :step1_new
        post :step1_create
      end
    end
  end

  resources :experiment_items, only: [:update, :destroy]

  resources :experiment_consolidation_wizards, :only => [] do
    collection do
    end
    member do
      get :step1
      put :step1_save

      get :step2

      get :step3_create
      get :step3_edit
      post :step3_reset
      post :step3_update

      get :step4_new
      get :step4_preview
      put :step4_create
      post :step4_create
      put :finalize
      post :finalize

      get :step5
    end
  end

  resources :experiment_order_wizards, only: [] do
    collection do
      get :abandon
    end
    member do
      put :step1_update
      get :step1_edit
      get :step2
      get :step3
      get :step4
      post :confirm
      get :abandon
    end
  end



  resources :task_output_files, :only => [:new, :show, :create] do
    member do
      put :create
      post :create
      get :renew_form
      get :preview
    end
  end

  resources :output_file_templates do
    collection do
      get :help
    end
  end

  resources :rl_results do
    member do
      get :result
    end
    collection do
      get :pivot
    end
  end

  resources :dilution_maps do
    collection do
      post :renew_form
      post :build_wells
      put :renew_form
      put :build_wells
    end
  end


  resources :task_barcodes, :except => [:update, :edit] do
    collection do
      get :show_collection
    end

  end

  resources :cdb_samples, :controller => 'rl_sample'

  resources :rl_samples do
    member do
      get :sample

      resource :query, :controller => 'rl_sample_query' do
        collection do
          post :add_columns
          get :update_options
        end
      end
    end

  end

  resources :cdb_methods, :controller => 'rl_method'

  resources :rl_methods do
    member do
      get :method
    end
  end

  resources :process_version_file_templates

  scope :module => "organize" do


    resources :queue_items do
      collection do
        get :packages
        get :results
        get :new_task
        get :work
        get :upload
        post :upload

        resources :carts, :as => 'queue_carts', :controller => 'queue_item_carts' do
          member do
            get :new_task
            post :run
            get :renew_form
          end
        end

      end
    end


    resources :outline_queues do
      member do
        get :orders
      end
    end

  end

  resources :tasks do

    resources :task_barcodes, :only => [:index]

    resources :dilution_slots,
              :only => [:new] do
      collection do
        get :show
        put :create
        post :update
      end
    end

    collection do
      get :results
      post :refresh # extra call to allow for form refresh
    end
    member do
      get :sheet
      get :copy
      get :update_preview_and_show
      post :select
      post :assign_member_to
      get :assign
      post :assign
      get :update_row
      get :print
      get :flexible
      get :update_queue
      get :clear
      get :remove
      post :remove
      get :results
      get :notify
      get :close
      get :fill
      get :recalc
    end
  end

  #TODO: this is just a subclass of Task. We should be re-using the Task routes
  resources :experiments, :controller => 'tasks' do
    resources :task_barcodes, :only => [:index]
    collection do
      get :results
      post :refresh # extra call to allow for form refresh
    end
    member do
      get :sheet
      get :copy
      get :update_preview_and_show
      get :select
      post :select
      get :assign
      post :assign
      get :update_row
      get :print
      get :flexible
      get :update_queue
      get :clear
      get :remove
      post :assign_member_to
      post :remove
      get :results
      get :notify
      get :close
      get :fill
      get :recalc
    end
  end

end

app/controllers/experiment_items_controller.rb
#
# = Experiment Order Wizard Controller
#
# Copyright © The Edge Software Consultancy 2006-2013 All rights reserved
# See license agreement for additional rights
#
class ExperimentItemsController < ApplicationController


  use_authorization Role::MODULE_QUEUE,
                    Role::RIGHT_BUILD => [:update, :destroy]

  def update
    @result_task = ResultTask.find(params[:id])
    queue_items = QueueItem.find(params[:queue_item_ids] || [])
    if params[:remove]
      @result_task.delete_queue_items queue_items
    else
      @result_task.add_queue_items queue_items
    end
    @result_task.reload
    @result_task.check_capacities
    flash.now[:warning] = @result_task.warnings.join("<br/>") if @result_task.warnings.any?
  end

  def destroy
    @result_task = ResultTask.find(params[:id])
    @result_task.queue_items.clear
    @result_task.reload
    @result_task.check_capacities
    render :update
    flash.now[:warning] = @result_task.warnings.join("<br/>") if @result_task.warnings.any?
  end


end

app/views/experiment_items/_allocate_queue_items.html.erb
<div class="span9">
  <div class="row">
    <%= render partial: '/experiment_items/queue_items', locals: {outline_queue: outline_queue}  %>
  </div>
</div>
<div class="span3" style="display:none">
  <div id="experiment_items" >
    <%= render partial: '/experiment_items/experiment_items' %>
  </div>
  <br style="clear:both"/>
  <div id = 'add'>
    <%= link_to t('.add_to_experiment'),  '#', id: 'move_to_experiment', class: 'btn btn-primary'%>
  </div>
  <div id="no_items">
  <%= t('.no_queue_items') %>
  </div>

  <div id = 'first_n'>
    <div class="container_fluid">
      <div class="row pagination-centered">
        <div class="input-prepend">
          <%= link_to t('.allocate'),  '#', id: 'select_items', class: 'btn btn-primary'%>
        </div>
        <div class="input-prepend">
          <%= number_field_tag('items', 1,:min => '1',:max=>'50', :class=>'no_bottom_margin span10', id: 'number_of_items')  %>
        </div>
        <div class="input-prepend">
          <label> <%= t('.items_from_queue')%></label>
        </div>
      </div>
    </div>
   </div>

</div>


<%= content_for :ext_on_ready do %>

    function move_items(queue_item_ids)
    {

        jQuery.ajax({type: "PUT",
                url: "<%= experiment_item_url(@result_task)%>",
                dataType: 'script',
                data: { queue_item_ids: queue_item_ids},
                success: function (result) {
                    Ext.getCmp("ExperimentQueryPanel").store.load();
                    Ext.getCmp("ExperimentQueryPanel").resetSelection();
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(thrownError);
                    alert(xhr.responseText);
                }
        });
    }

    jQuery(document).ready(function(){
        jQuery('#select_items').click(function() {
            var number_of_items = parseInt( jQuery('#number_of_items').val() );
            var queue_item_ids = Ext.getCmp("ExperimentQueryPanel").getItems(number_of_items);
            move_items(queue_item_ids);
        });

        jQuery('#move_to_experiment').click(function() {
            var queue_item_ids = Ext.getCmp("ExperimentQueryPanel").selected_list;
            move_items(queue_item_ids);
        });

        jQuery('div.span3').show();
        jQuery('div#add').hide();
        jQuery('div#no_items').hide();
    });
<% end %>

<div id="js_tag">

</div>

app/views/experiment_items/_experiment_items.html.erb
<legend><%= t('.in_experiment') %> </legend>
<label>
  No. of items: <%= @result_task.queue_items.length %>
</label>
<label>
  <% if @result_task.process.try(:max_queue_items) %> Capacity: <%= @result_task.process.try(:max_queue_items) %> <%end%>
</label>


<table id='experiment_table_id' class='table table-striped table-condensed' style="position:relative">
  <tr>
    <th><%= t('name') %></th>

    <th><%= link_to 'All',  '#', id: 'All'%></th>
  </tr>
  <% @result_task.queue_items.each do |queue_item| %>
    <tr>
      <td class="popup" ><%=queue_item.name%>
        <table class="modal_popup">
          <tr><th colspan="2"><%= t('.queue_item_details') %></th></tr>
          <tr><td><%= t('.state') %></td><td><%=queue_item.state.name %></td></tr>
          <tr><td><%= t('.service') %></td><td><%=queue_item.queue.name %></td></tr>
          <tr><td><%= t('.method') %></td><td><%=queue_item.outline_method.try(:name) %></td></tr>
          <tr><td><%= t('created_at') %></td><td><%= short_date(queue_item.created_at) %></td></tr>
          <tr><td><%= t('.data_priority') %></td><td><%=queue_item.data_priority.try(:name) %></td></tr>
          <tr><td><%= t('.request') %></td><td><%=queue_item.request_name %></td></tr>
        </table>
      </td>
      <td><%= link_to 'Remove',  '#', id: "item_#{queue_item.id}", class: 'move_to_queue'%></td>
    </tr>
  <% end %>
</table>



<%= content_for :ext_on_ready do %>
    jQuery('.modal_popup').hide();

    jQuery('document').ready(function(){
        jQuery('.popup').hover(
        function(){
                jQuery(this).find('table').show();
            },
            function(){
                jQuery(this).find('table').hide();
        });
    });

    jQuery('.move_to_queue').click(function() {
        var queue_item_ids = [];
        queue_item_ids[0] = jQuery(this).attr('id').substr(5);
        jQuery.ajax({type: "PUT",
            url: "<%= experiment_item_path(id: @result_task.id)%>",
            dataType: 'script',
            data: { remove: true, queue_item_ids: queue_item_ids},
            success: function (result) {
                Ext.getCmp("ExperimentQueryPanel").store.load();
                jQuery('#no_items').hide();
            }
        });
    });

    jQuery('#All').click(function() {
        jQuery.ajax({type: "DELETE",
            url: "<%= experiment_item_path(id: @result_task.id)%>",
            dataType: 'script',
            success: function (result) {
                Ext.getCmp("ExperimentQueryPanel").store.load();
            }
        });
    });

<% end %>

app/views/experiment_items/_queue_items.html.erb
<% content_for :header do%>
    <link rel="stylesheet" type="text/css" href="/javascripts/ext/plugins/filter_bar/resources/css/uxs.css" />
    <link rel="stylesheet" type="text/css" href="/javascripts/ext/plugins/filter_bar/resources/css/overrides.css" />
    <link rel="stylesheet" type="text/css" href="/javascripts/ext/plugins/filter_bar/resources/css/app.css" />

    <script type="text/javascript" src="/javascripts/ext/plugins/filter_bar/ux/form/field/ClearButton.js"></script>
    <script type="text/javascript" src="/javascripts/ext/plugins/filter_bar/ux/form/field/OperatorButton.js"></script>
    <script type="text/javascript" src="/javascripts/ext/plugins/filter_bar/ux/form/field/TextOperatorButton.js"></script>
    <script type="text/javascript" src="/javascripts/ext/plugins/filter_bar/ux/form/field/DateOperatorButton.js"></script>
    <script type="text/javascript" src="/javascripts/ext/plugins/filter_bar/ux/grid/column/ActionPro.js"></script>
    <script type="text/javascript" src="/javascripts/ext/plugins/filter_bar/ux/grid/FilterBar.js"></script>
    <script type="text/javascript" src="/javascripts/ext/plugins/filter_bar/ux/grid/AutoResizer.js"></script>
<% end %>



<div id="gridcontents"></div>

<% content_for :ext_on_ready do %>
    <%= QueryEngine::ExtMapper.new(@query).experiment_grid( 'gridcontents', {outline_queue_id: outline_queue.id }) %>
<% end %>

app/views/experiment_items/update.js.erb
jQuery('#messages').html("<%= escape_javascript(render :partial => 'shared/messages')%>");

<% if @result_task.errors.empty? %>
    Ext.getCmp("ExperimentQueryPanel").store.load();
    Ext.getCmp("ExperimentQueryPanel").resetSelection();
    jQuery('#experiment_items').html('<%= escape_javascript(render partial: "experiment_items/experiment_items")%>');
    jQuery('#js_tag').html('<script type="text/javascript"><%= escape_javascript(render partial: "shared/ajax_javascripts")%></script>');
<% end %>