config/routes.rb
B5::Application.routes.draw do

  scope :module => "organize" do

    resources :queue_items_cart,  :only => [:show,:update],  :controller => 'queue_items_cart' do

      member do
        post :assign
        post :cart
        post :order
        post :run
        post :redo
        post :list
        post :update
      end
    end

    resources :queue_items do
      collection do
        get :packages
        get :results
        get :new_task
        get :work
        get :upload
        post :upload
      end
      member do
        get :is_reason_required
      end


    end
  end

  resources :outline_queues do
    resource :experiment_order_wizard, only: [] do
      collection do
        get :step1_new
        post :step1_create
      end
    end
  end

  resources :experiment_items, only: [:update, :destroy]

  resources :experiment_consolidation_wizards, :only => [] do
    collection do
    end
    member do
      get :step1
      put :step1_save

      get :step2

      get :step3_create
      get :step3_edit
      post :step3_reset
      post :step3_update

      get :step4_new
      get :step4_preview
      put :step4_create
      post :step4_create
      put :finalize
      post :finalize

      get :step5
    end
  end

  resources :experiment_order_wizards, only: [] do
    collection do
      get :abandon
    end
    member do
      put :step1_update
      get :step1_edit
      get :step2
      get :step3
      get :step4
      post :confirm
      get :abandon
    end
  end



  resources :task_output_files, :only => [:new, :show, :create] do
    member do
      put :create
      post :create
      get :renew_form
      get :preview
    end
  end

  resources :output_file_templates do
    collection do
      get :help
    end
  end

  resources :rl_results do
    member do
      get :result
    end
    collection do
      get :pivot
    end
  end

  resources :dilution_maps do
    collection do
      post :renew_form
      post :build_wells
      put :renew_form
      put :build_wells
    end
  end


  resources :task_barcodes, :except => [:update, :edit] do
    collection do
      get :show_collection
    end

  end

  resources :cdb_samples, :controller => 'rl_sample'

  resources :rl_samples do
    member do
      get :sample

      resource :query, :controller => 'rl_sample_query' do
        collection do
          post :add_columns
          get :update_options
        end
      end
    end

  end

  resources :cdb_methods, :controller => 'rl_method'

  resources :rl_methods do
    member do
      get :method
    end
  end

  resources :process_version_file_templates

  scope :module => "organize" do


    resources :queue_items do
      collection do
        get :packages
        get :results
        get :new_task
        get :work
        get :upload
        post :upload

        resources :carts, :as => 'queue_carts', :controller => 'queue_item_carts' do
          member do
            get :new_task
            post :run
            get :renew_form
          end
        end

      end
    end


    resources :outline_queues do
      member do
        get :orders
      end
    end

  end

  resources :tasks do

    resources :task_barcodes, :only => [:index]

    resources :dilution_slots,
              :only => [:new] do
      collection do
        get :show
        put :create
        post :update
      end
    end

    collection do
      get :results
      post :refresh # extra call to allow for form refresh
    end
    member do
      get :sheet
      get :copy
      get :update_preview_and_show
      post :select
      post :assign_member_to
      get :assign
      post :assign
      get :update_row
      get :print
      get :flexible
      get :update_queue
      get :clear
      get :remove
      post :remove
      get :results
      get :notify
      get :close
      get :fill
      get :recalc
    end
  end

  #TODO: this is just a subclass of Task. We should be re-using the Task routes
  resources :experiments, :controller => 'tasks' do
    resources :task_barcodes, :only => [:index]
    collection do
      get :results
      post :refresh # extra call to allow for form refresh
    end
    member do
      get :sheet
      get :copy
      get :update_preview_and_show
      get :select
      post :select
      get :assign
      post :assign
      get :update_row
      get :print
      get :flexible
      get :update_queue
      get :clear
      get :remove
      post :assign_member_to
      post :remove
      get :results
      get :notify
      get :close
      get :fill
      get :recalc
    end
  end

end

app/models/output_file_template.rb
class OutputFileTemplate < ActiveRecord::Base

  acts_as_dictionary

  has_many :process_version_file_templates

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :content

  has_many :process_versions

  def content=(text)
    super(text)
    self.length = text.length
  end

end

app/controllers/experiment_consolidation_wizards_controller.rb
#
# = Experiment Consolidation Wizard Controller
#
# Copyright © The Edge Software Consultancy 2006-2013 All rights reserved
# See license agreement for additional rights
#
class ExperimentConsolidationWizardsController < ApplicationController
  layout 'wizard'

  include Biorails::WizardExtras

  use_authorization Role::MODULE_QUEUE,
                    Role::RIGHT_BUILD => [
                        :step1,
                        :step2, :step2_create, :step2_edit, :step2_update,
                        :step3_new, :step3_preview, :step3_create,
                        :step4
                    ]

  before_filter :get_result_task
  before_filter :display_capacity_warnings

  # Edit Experiment
  #
  # Basic details for run for confirmation
  #
  def step1
    @state_counts = @result_task.queue_items.count(group:'state_id')
    @states = State.where(id:@state_counts.keys).order('level_no','name')
    render locals: {outline_queue: @result_task.queue}
  end


  def step1_save
    unless @result_task.update_attributes(params[:task])
      return render :step1
    end
    if params[:remove_state_id]
      @result_task.reload
      @result_task.task_remove_queue_items(@result_task.queue_items.in_state_id(params[:remove_state_id].keys))
    end
    redirect_to step2_experiment_consolidation_wizard_path(@result_task)
  end

  #
  # Task sheet Display for Editing and confirmation
  #
  def step2

  end

  #
  # On 'Next' in step 1
  #
  # Consolidation is carried out
  # Then on to step2_edit
  #
  # TODO skip straight to step4_new when there is no dilution map
  #
  def step3_create
    if @result_task.dilution_slots.any?
      redirect_to step3_edit_experiment_consolidation_wizard_path(@result_task)

    elsif TaskConsolidation.is_suitable_task?(@result_task)
      @job_id = TaskConsolidation.async_run(
          {
              task: @result_task,
              success_url: step3_edit_experiment_consolidation_wizard_path(@result_task),
              fail_url: step2_experiment_consolidation_wizard_path(@result_task)
          }
      )
      redirect_to(job_path(:action => 'waiting', :id => @job_id, :redirect => true))
    else
      if @result_task.process.process_version_file_templates.any?
        redirect_to step4_new_experiment_consolidation_wizard_path(@result_task)
      else
        redirect_to step5_experiment_consolidation_wizard_path(@result_task)
      end
    end
  end

  #
  # When step2_create is complete
  #
  # This shows the user their consolidation plan
  # and allows them to re-arrange the slots
  #
  def step3_edit
    @plate_data_store = PlateDataStore.new(@result_task.id)
    @dilution_slots = @result_task.dilution_slots.by_row
  end

  def step3_reset
    @plate_data_store = PlateDataStore.new(params[:id])
  end

  #
  # On 'Next' for step 2
  #
  # * enact any re-arranged slots
  #
  def step3_update
    if @result_task.process.process_version_file_templates.any?
      success_url = step4_new_experiment_consolidation_wizard_path(@result_task)
    else
      success_url = step5_experiment_consolidation_wizard_path(@result_task)
    end
    @job_id = TaskConsolidation.async_rearrange(
        {
            task: @result_task,
            success_url: success_url,
            slot_positions: JSON.parse(params[:dilution_slot_positions]),
            fail_url: step3_edit_experiment_consolidation_wizard_path(@result_task)
        }
    )
    redirect_to(job_path(:action => 'waiting', :id => @job_id, :redirect => true))
  end

  def step4_new

  end

  def step4_preview
    @process_version_file_template = ProcessVersionFileTemplate.find(params[:process_version_file_template_id])
    @result_task.process_version_file_template_id = params[:process_version_file_template_id]
    @preview_text = @result_task.generate_output_file_content.split("\n")[0...5].join("\n")
  end

  def step4_create
    @result_task.process_version_file_template_ids = params[:task][:process_version_file_template_ids].collect { |k, v| k }
    @job_id = Biorails::TaskFinalizeJob.async_fill_output_files(
        {
            :task => @result_task,
            :user_id => User.current.id,
            :fail_url => step4_new_experiment_consolidation_wizard_path(@result_task),
            :success_url => step5_experiment_consolidation_wizard_path(@result_task)
        }
    )
    redirect_to(job_path(:action => 'waiting', :id => @job_id, :redirect => true))
  end

  def step5
    @dilution_slots = @result_task.dilution_slots.by_row
    @plate_data_store = PlateDataStore.new(@result_task.id)
  end

  def finalize
    begin
      @result_task.tasks.each do |child_task|
        child_task.cascade_items(@result_task.items) # copy samples and setup to children
        child_task.reload
        child_task.to_html(false)
      end
      @result_task.sync_content_to_filesystem
      @result_task.reload
      @result_task.set_completed
#      @result_task.queue_items.each{|q|q.set_state(State.lookup("ready"))}
      flash[:success] = t('experiment_consolidation_wizards.finalise_success')
      redirect_to task_path(@result_task)
    rescue => er
      logger.warn er.message
      logger.info er.backtrace.join("\n")
      flash[:error] = er.message
      redirect_to step5_experiment_consolidation_wizard_path(@result_task)
    end
  end

  private

  def display_capacity_warnings
    if @result_task
      @result_task.check_capacities
      if @result_task.warnings.any?
        flash.now[:warning] = @result_task.warnings.join("<br/>")
      end
    end
  end

  def get_result_task
    @result_task = ResultTask.find(params[:id])
    @outline_queue = @result_task.queue
    # this makes some partials from the dilution slots controller work.
    @task = @result_task
  end

end

app/helpers/experiment_consolidation_wizards_helper.rb
module ExperimentConsolidationWizardsHelper

  # This class converts a flat TSV plain text files into an html table
  def display_tsv(source_text)
    table_content = ""

    header_row = "<tr><th>#{source_text.split("\n")[0].split("\t").join("</th><th>")}</th></tr>"
    source_text.split("\n")[1..-1].each do |row|
      table_content << '<tr>'
      row.split("\t").each do |cell|
        table_content << "<td>#{cell}</td>"
      end
      table_content << '</tr>'
    end
    return <<HTML
    <table class="table" style="background-color:white;">
      <thead>
        #{header_row}
      </thead>
      <tbody>
        #{table_content}
      </tbody>
    </table>
HTML
  end

end

app/views/experiment_consolidation_wizards/_consolidation_result_table.html.erb
<div id="drag">
  <table class="table-condensed table-bordered consolidation_table"
         id="consolidation_table">
    <thead>
      <tr>
        <%# @result_task.dilution_map.dilution_map_slots.order('position asc').each_with_index do |dilution_map_slot, idx| %>
        <% @result_task.dilution_map.length.times do |idx| %>
          <% dilution_map_slot = @result_task.dilution_map.dilution_map_slots.detect{|x| x.position == idx} %>
          <th>
            <%= idx + 1 %>
            <br/>

            <%= dilution_map_slot ? dilution_map_slot.slot_type : 'blank' %>
          </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @plate_data_store.dilution_slot_rows.each do |row| %>
        <tr>
          <% @result_task.dilution_map.length.times do |cell| %>
            <% dilution_slot = row.detect { |x| x.column_no == cell if x } %>
            <% if dilution_slot %>
              <% if dilution_slot.slot_type == 'samp' %>
                <% kls = dilution_slot.marked ? 'marked' : '' %>
                <td>
                  <div id="<%= dilution_slot.id %>"
                       title="<%= dilution_slot.summary %>"
                       class="drag <%= kls %> samp"
                       style="background-color:<%= dilution_slot.colour %>;">
                    <%= dilution_slot.source_string %>
                  </div>
                </td>
              <% else %>
                <td>
                  <div id="<%= dilution_slot.id %>"
                       class="<%= dilution_slot.slot_type %>"
                       title="<%= dilution_slot.summary %>">
                    <%= dilution_slot.source_string %>
                  </div>
                </td>
              <% end %>
            <% else %>
              <td class="empty"></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/experiment_consolidation_wizards/_consolidation_results.html.erb
<div class="biorails_form_wrapper" style="padding-left:30px;padding-bottom:10px;">

  <% @plate_data_store.coasts_plates.in_groups_of(2).each do |row_of_plates| %>
    <div class="row">
      <% row_of_plates.each do |coasts_plate| %>
        <% if coasts_plate %>
          <div class='span6'>
            <%= render :partial => 'coasts_plates/thumbnail_diagram',
                       :locals => {
                         :coasts_plate => coasts_plate,
                         :index => (@result_task.colour_index_for(coasts_plate.plate_code)),
                         :mode => 'coord'
                       } %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <% if @plate_data_store.scanned_coasts_plate_wells.any? %>
    <div class="row">
      <div class='span6'>
        <%= render :partial => 'dilution_slots/well_diagram' %>
      </div>
    </div>
  <% end %>

  <% if @plate_data_store.cdb_samples.any? %>
    <div class="row">

      <div class='span6'>
        <%= render :partial => 'dilution_slots/sample_diagram' %>
      </div>
    </div>
  <% end %>

</div>

<div class="consolidation_table_holder">
  <%= render 'consolidation_result_table' %>
</div>

app/views/experiment_consolidation_wizards/_shared_buttons.html.erb
<%= button_to t('wizard.abandon'),
      task_url(@result_task),
      :class => 'wizard_button_abandon btn-link',
      :confirm =>  t('.abandon_text'), method: :get %>

<%= link_to t('.checkin'),
              new_task_barcode_path(task_id: @result_task.id),
              :class => 'wizard_button_extra1 btn btn-link',
              :confirm =>  t('.abandon_goto_checkin'), method: :get %>

<%= link_to t('.replan'),
              outline_queue_management_path(@outline_queue,task_id:@result_task.id),
              :class => 'wizard_button_extra2 btn btn-link',
              :confirm => t('.abandon_goto_replan'), method: :get %>

app/views/experiment_consolidation_wizards/_step1_form.html.erb
<%= biorails_form_for @result_task, :as => 'task',:url => step1_save_experiment_consolidation_wizard_path(@result_task) do |form| %>

    <%= form.hidden_field :parent_id %>
    <%= form.hidden_field :project_id %>
    <%= form.hidden_field :project_element_id %>
    <%= form.hidden_field :lock_version %>

    <fieldset>
      <legend><%=@result_task.name%></legend>
      <%= form.text_field :name,disabled:true %>
      <%= form.text_area :description, :rows => 3 %>
    <%= form.select_member(:assigned_member_id, @result_task.project_element) %>
    <%= form.date_field :started_on %>
    <%= form.date_field :expected_on %>
    </fieldset>


    <fieldset>
      <legend>Queue items by state</legend>


      <% @states.each do |state| %>

          <div class="clearfix control-group ">
            <label class="control-label"><%= state.name %></label>
            <div class="controls ">
              <% if state.name.downcase == 'delivered' %>
                  <%= "#{@state_counts[state.id]} "%>
              <% else %>
                  <label class="control-label"><%= "#{@state_counts[state.id]}"%></label>
                  <label class="checkbox">
                    <span><input type="checkbox" name="remove_state_id[<%=state.id%>]"> Remove?</span>
                    <span class="help-inline"><%=@result_task.queue_items.select{|i|i.state_id == state.id}.collect{|i|i.name}.join(" , ")%></span>
                  </label>

              <% end %>
            </div>
          </div>

      <%end%>

      <%= form.labelled_text "Unmanaged Items",@result_task.contexts.select{|i|i.result_queue_item.nil?}.size %>

      <div class="clearfix control-group ">
        <label class="control-label">Total sheet rows</label>
        <div class="controls ">
          <%= @result_task.contexts.size %>
          <span class="help-inline">
             <%= test_task_in_size_limits(@result_task)  %>
          </span>
        </div>
      </div>

    </fieldset>

    <%= form.submit t('wizard.next_button_name'), :class => 'wizard_button_next btn btn-success' %>

<% end %>

app/views/experiment_consolidation_wizards/_step2_sheet.html.erb
<div id="<%=task.dom_id('div')%>"> </div>
<script>
    var sheet = null;

    Ext.onReady(
            function(){

                var w = jQuery('#<%=task.dom_id('grid')%>').parent().width();

                sheet = Ext.create('Ext.biorails.TaskSheetPanel', {
                    id: '<%=task.dom_id(:grid)%>',
                    title:null,
                    renderTo: '<%=task.dom_id('div')%>',
                    process_version_id: <%=task.process_version_id%>,
                    task_id: <%=task.id%>,
                    columns: <%=raw ext_columns(task.process).to_json%>,
                    data: <%=raw task.sheet.to_ext.to_json%>,
                    outline_method_list: [],
                    outline_parameter_list: <%=raw task.allowed_parameter_options.to_json %>,
                    sheet_url: '<%= task_sheet_path(task)%>',
                    goto_url: '<%=step3_create_experiment_consolidation_wizard_path(task)%>',
                    loadMask: true,
                    minWidth: 500,
                    minHeight: 500,
                    width: w,
                    columnLines: true
                });
            });
</script>

app/views/experiment_consolidation_wizards/_task_summary.html.erb
<span class="help-inline">
  <%= t('.finalize_summary') %>
</span>

<dl class="dl-horizontal">

  <dt><%= Task.human_attribute_name(:name) %></dt>
  <dd><%= @result_task.name %></dd>

  <dt><%= Task.human_attribute_name(:description) %></dt>
  <dd><%= @result_task.description %></dd>

  <dt><%= Task.human_attribute_name(:process_version_id) %></dt>
  <dd><%= @result_task.process.name %></dd>

  <dt><%= Task.human_attribute_name(:state_id) %></dt>
  <dd><%= @result_task.state_name %></dd>

</dl>

<%= raw @result_task.task_sheet_html %>

app/views/experiment_consolidation_wizards/_wizard_menu.html.erb
<% content_for :wizard_title do %>
  <%= t('.wizard_title') %>
<% end %>

<% run_step3 = TaskConsolidation.is_suitable_task?(@result_task) %>
<% run_step4 = @result_task.process.process_version_file_templates.any?  %>

<% content_for :wizard_menu do %>
    <%= wizard_menu_step(1, step, t('.step1')) %>
    <%= wizard_menu_step(2, step, t('.step2')) %>
  <%= wizard_menu_step(3, step, run_step3 ? t('.step3') : t('.step3_disabled') ) %>
  <%= wizard_menu_step(4, step, run_step4 ? t('.step4') : t('.step4_disabled')) %>
  <%= wizard_menu_step(5, step, t('.step5')) %>
<% end %>

app/views/experiment_consolidation_wizards/step1.html.erb
<%= content_for :messages do %>
  <%= render partial: 'shared/messages', :locals => {:objects => ['result_task']} %>
<% end %>

<%= render partial: 'step1_form' %>

<%= render partial: 'shared_buttons' %>
<%= render partial: 'wizard_menu', :locals => {:step => 1} %>

app/views/experiment_consolidation_wizards/step2.html.erb
<%= content_for :messages do %>
    <%= render partial: 'shared/messages', :locals => {:objects => ['result_task']} %>
<% end %>

<%= render partial: 'step2_sheet',locals: {task: @result_task} %>
<%= render partial: 'shared_buttons' %>
<%= render partial: 'wizard_menu', :locals => {:step => 2} %>

<input value= "<%=t('wizard.next_button_name')%>"
       id="task_save"
       name="task_save"
       class="btn btn-success wizard_button_next"
       type="submit"/>

<script>
    jQuery( document ).ready(function() {
        console.log( "Override save button" );
        jQuery('#task_save').click(function(){
            sheet.save();
        });
    });

</script>

<%= wizard_back_button(step1_experiment_consolidation_wizard_path(@result_task)) %>

app/views/experiment_consolidation_wizards/step3_edit.html.erb
<%= content_for :messages do %>
  <%= render partial: 'shared/messages', :locals => {:objects => ['result_task']} %>
<% end %>

<%= render partial: 'shared_buttons' %>
<%= render partial: 'wizard_menu', :locals => {:step => 3} %>

<%= wizard_back_button(step2_experiment_consolidation_wizard_path(@result_task)) %>

<div class="biorails_form_wrapper">
  <% @plate_data_store.coasts_plates.in_groups_of(2).each do |row_of_plates| %>
    <div class="row" id="plate_holder">
      <% row_of_plates.each do |coasts_plate| %>
        <% if coasts_plate %>
          <div class='span6'>
            <%= render :partial => 'coasts_plates/thumbnail_diagram',
                       :locals => {
                         :coasts_plate => coasts_plate,
                         :index => (@result_task.colour_index_for(coasts_plate.plate_code)),
                         :mode => 'coord'
                       } %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <% if @plate_data_store.scanned_coasts_plate_wells.any? %>
    <div class="row" id="plate_holder">
      <div class='span6'>
        <%= render :partial => 'dilution_slots/well_diagram' %>
      </div>
    </div>
  <% end %>

  <% if @plate_data_store.cdb_samples.any? %>
    <div class="row" id="plate_holder">

      <div class='span6'>
        <%= render :partial => 'dilution_slots/sample_diagram' %>
      </div>
    </div>
  <% end %>

  <div class="row" id="result_holder">
    <div class='span12'>
      <h2><%= t('.result_title') %></h2>
      <span class="help inline"><%= t('.drag_help') %></span>

      <div class="consolidation_table_holder">
        <%= render 'consolidation_result_table' %>
      </div>

      <div>
        <%= link_to t('.reset'), '#', id: 'reset', :class => "btn btn-primary" %>
      </div>
    </div>
  </div>

  <%= form_tag(step3_update_experiment_consolidation_wizard_path(@result_task), method: :post, class: 'form-horizontal') do %>
    <%= hidden_field_tag(:dilution_slot_positions) %>
    <%= submit_tag t('wizard.next_button_name'), :class => 'wizard_button_next btn btn-success' %>
  <% end %>

</div>


<%= content_for :header do %>
  <%= javascript_include_tag 'redips-drag-min' %>
  <%= stylesheet_link_tag 'bi/plate_thumbs' %>

  <script type="text/javascript">
    function set_slot_params() {
      jQuery("#dilution_slot_positions").val(JSON.parse(REDIPS.drag.saveContent('consolidation_table', 'json')));
    }


    function reset_slots() {
      jQuery.post("<%=step3_reset_experiment_consolidation_wizard_path(@result_task)%>");
    }

    <%= render :partial => 'init_redips_drag.js' %>
  </script>

<% end %>

<% content_for :jquery_on_ready do %>
  set_slot_params();
  REDIPS.drag.event.dropped = set_slot_params;
  jQuery('#reset').click(reset_slots);
<% end %>

app/views/experiment_consolidation_wizards/step3_reset.js.erb
jQuery('.consolidation_table_holder').html("<%= escape_javascript(render :partial => 'consolidation_result_table') %>");
<%= render :partial => 'init_redips_drag.js' %>
jQuery('#messages').html("<%=escape_javascript(render :partial => 'shared/messages')%>");

app/views/experiment_consolidation_wizards/step4_new.html.erb
<%= content_for :messages do %>
  <%= render partial: 'shared/messages', :locals => {:objects => ['result_task']} %>
<% end %>

<%= render partial: 'shared_buttons' %>
<%= render partial: 'wizard_menu', :locals => {:step => 4} %>

<%= wizard_back_button(step3_edit_experiment_consolidation_wizard_path(@result_task)) %>


<% biorails_form_for @result_task, :url => step4_create_experiment_consolidation_wizard_path(@result_task) do |form| %>

  <table class="table table-condensed">
    <thead>
      <tr>
        <th><%= ProcessVersionFileTemplate.human_attribute_name(:name) %></th>
        <th><%= ProcessVersionFileTemplate.human_attribute_name(:output_file_template_id) %></th>
        <th><%= t('actions') %></th>
      </tr>
    </thead>
    <tbody>
      <% @result_task.process.process_version_file_templates.each do |process_version_file_template| %>
        <tr>
          <td>
            <%= check_box_tag(
                  "task[process_version_file_template_ids[#{process_version_file_template.id}]]",
                  '1',
                  true
                ) %>
            <%= process_version_file_template.name %>
          </td>
          <td><%= process_version_file_template.output_file_template.name %> </td>
          <td>
            <%= link_to t('preview'), '#',
                        :class => 'preview_link',
                        'data-id' => process_version_file_template.id %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= form.submit t('wizard.next_button_name'), :class => 'btn btn-success wizard_button_next' %>

  <div id="previews" style="display:none;">
    <h2><%= t('.previews_title') %></h2>
    <p><%= t('.previews_help') %></p>

  </div>

<% end %>



<script type="text/javascript">

  jQuery('.preview_link').on('click', function(e){
    e.preventDefault();
    jQuery('.preview_link').show();
    jQuery(this).hide();
    jQuery('.preview').hide();
    var preview_id = "#preview_" + jQuery(this).data('id');
    if (jQuery(preview_id).length == 0) {
      jQuery.ajax({url: "<%= step4_preview_experiment_consolidation_wizard_path(@result_task) %>",
        dataType: 'script',
        data: { process_version_file_template_id: jQuery(this).data('id') }
      });
    } else {
      jQuery(preview_id).show();
    }
  });
</script>

app/views/experiment_consolidation_wizards/step4_preview.js.erb
jQuery('#previews').show();
jQuery('#previews').append("<div class='preview' id='preview_<%= @process_version_file_template.id %>'>"+
                           "<h3><%= @process_version_file_template.name %></h3>"+
                           "<%=escape_javascript(display_tsv(@preview_text).html_safe) %>" +
                           "</div>");

app/views/experiment_consolidation_wizards/step5.html.erb
<%= content_for :messages do %>
  <%= render partial: 'shared/messages', :locals => {:objects => ['result_task']} %>
<% end %>
<%= render partial: 'wizard_menu', :locals => {:step => 5} %>
<%= render partial: 'shared_buttons' %>

<%= content_for :header do %>
  <%= stylesheet_link_tag 'bi/plate_thumbs' %>
<% end %>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#summary" role="tab" data-toggle="tab"><%= t('.summary') %></a></li>
  <% if @result_task.dilution_map %>
    <li><a href="#consolidation" role="tab" data-toggle="tab"><%= t('.consolidation_title') %></a></li>
  <% end %>
  <% if @result_task.process.process_version_file_templates.any? %>
    <li><a href="#folder_content" role="tab" data-toggle="tab"><%= t('.files_title') %></a></li>
  <% end %>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="summary">
    <div id="task_sheet">
      <%= render 'task_summary' %>
    </div>
  </div>

  <div class="tab-pane" id="consolidation">
    <% if @result_task.dilution_map %>
      <%= render 'consolidation_results' %>
    <% end %>

  </div>

  <% if @result_task.process.process_version_file_templates.any? %>
    <div class="tab-pane" id="folder_content">
      <%= render 'contents_table' %>
    </div>
  <% end %>
</div>


<%= wizard_next_button(finalize_experiment_consolidation_wizard_path(@result_task), 'post', t('.finalise')) %>

<% if @result_task.process.process_version_file_templates.any? %>
  <%= wizard_back_button(step4_new_experiment_consolidation_wizard_path(@result_task)) %>
<% else %>
  <%= wizard_back_button(step3_edit_experiment_consolidation_wizard_path(@result_task)) %>
<% end %>