config/routes.rb
B5::Application.routes.draw do

  scope :module => "organize" do

    resources :queue_items_cart,  :only => [:show,:update],  :controller => 'queue_items_cart' do

      member do
        post :assign
        post :cart
        post :order
        post :run
        post :redo
        post :list
        post :update
      end
    end

    resources :queue_items do
      collection do
        get :packages
        get :results
        get :new_task
        get :work
        get :upload
        post :upload
      end
      member do
        get :is_reason_required
      end


    end
  end

  resources :outline_queues do
    resource :experiment_order_wizard, only: [] do
      collection do
        get :step1_new
        post :step1_create
      end
    end
  end

  resources :experiment_items, only: [:update, :destroy]

  resources :experiment_consolidation_wizards, :only => [] do
    collection do
    end
    member do
      get :step1
      put :step1_save

      get :step2

      get :step3_create
      get :step3_edit
      post :step3_reset
      post :step3_update

      get :step4_new
      get :step4_preview
      put :step4_create
      post :step4_create
      put :finalize
      post :finalize

      get :step5
    end
  end

  resources :experiment_order_wizards, only: [] do
    collection do
      get :abandon
    end
    member do
      put :step1_update
      get :step1_edit
      get :step2
      get :step3
      get :step4
      post :confirm
      get :abandon
    end
  end



  resources :task_output_files, :only => [:new, :show, :create] do
    member do
      put :create
      post :create
      get :renew_form
      get :preview
    end
  end

  resources :output_file_templates do
    collection do
      get :help
    end
  end

  resources :rl_results do
    member do
      get :result
    end
    collection do
      get :pivot
    end
  end

  resources :dilution_maps do
    collection do
      post :renew_form
      post :build_wells
      put :renew_form
      put :build_wells
    end
  end


  resources :task_barcodes, :except => [:update, :edit] do
    collection do
      get :show_collection
    end

  end

  resources :cdb_samples, :controller => 'rl_sample'

  resources :rl_samples do
    member do
      get :sample

      resource :query, :controller => 'rl_sample_query' do
        collection do
          post :add_columns
          get :update_options
        end
      end
    end

  end

  resources :cdb_methods, :controller => 'rl_method'

  resources :rl_methods do
    member do
      get :method
    end
  end

  resources :process_version_file_templates

  scope :module => "organize" do


    resources :queue_items do
      collection do
        get :packages
        get :results
        get :new_task
        get :work
        get :upload
        post :upload

        resources :carts, :as => 'queue_carts', :controller => 'queue_item_carts' do
          member do
            get :new_task
            post :run
            get :renew_form
          end
        end

      end
    end


    resources :outline_queues do
      member do
        get :orders
      end
    end

  end

  resources :tasks do

    resources :task_barcodes, :only => [:index]

    resources :dilution_slots,
              :only => [:new] do
      collection do
        get :show
        put :create
        post :update
      end
    end

    collection do
      get :results
      post :refresh # extra call to allow for form refresh
    end
    member do
      get :sheet
      get :copy
      get :update_preview_and_show
      post :select
      post :assign_member_to
      get :assign
      post :assign
      get :update_row
      get :print
      get :flexible
      get :update_queue
      get :clear
      get :remove
      post :remove
      get :results
      get :notify
      get :close
      get :fill
      get :recalc
    end
  end

  #TODO: this is just a subclass of Task. We should be re-using the Task routes
  resources :experiments, :controller => 'tasks' do
    resources :task_barcodes, :only => [:index]
    collection do
      get :results
      post :refresh # extra call to allow for form refresh
    end
    member do
      get :sheet
      get :copy
      get :update_preview_and_show
      get :select
      post :select
      get :assign
      post :assign
      get :update_row
      get :print
      get :flexible
      get :update_queue
      get :clear
      get :remove
      post :assign_member_to
      post :remove
      get :results
      get :notify
      get :close
      get :fill
      get :recalc
    end
  end

end

app/views/experiment_orders/_cart_item_details.html.erb
<%= if order_profile.solid?
      render :partial => 'orders/form_items_dry', :locals => {:f => f, :order_profile => order_profile}
    elsif order_profile.standard_liquid?
      render :partial => 'orders/form_items_standard_liquid', :locals => {:f => f}
    elsif order_profile.custom_liquid?
      render :partial => 'orders/form_items_custom_liquid', :locals => {:f => f, :order_profile => order_profile}
    elsif order_profile.dissolution?
      render :partial => 'orders/form_items_dissolution', :locals => {:f => f}
    elsif order_profile.subways?
      render :partial => 'orders/form_items_subways', :locals => {:f => f, :order_profile => order_profile}
    end
%>

app/views/experiment_orders/_order_form.html.erb
<%= biorails_form_for(@order, url: experiment_orders_url(@task.id)) do |form| %>

    <%= form.labelled_text :task, @task.name%>
    <%= form.labelled_text :items, @task.queue_items.count%>

    <%= form.hidden_field :task_id %>
    <%= form.hidden_field :outline_queue_id %>

    <%= form.select :order_profile_id, options_for_select(order_profile_options(@outline_queue), :selected => @order.order_profile_id), {}, {id: 'order_profile_select'} %>

    <%= form.labelled_text OrderProfile.human_attribute_name(:amount_display), @order_profile.amount_display %>

    <% unless @order_profile.dissolution? %>
        <%= form.select :use_internal_recipient,
                        [
                                ['Internal', true],
                                ['External', false]
                        ],
                        {},
                        {:onchange => "switch_internal_external(); "} %>


        <div id='internal'>
          <%= form.combo_for_model :recipient_user_id, User, :required => true %>
        </div>
        <div id='external' style='display: none'>
          <%= form.combo_for_model :coasts_external_recipient_id, CoastsExternalRecipient, :required => true %>
        </div>
    <% end %>

    <%= render partial: 'cart_item_details', locals: {order_profile: @order_profile, f: form}%>
    <%= form.submit 'Order', :name => :submit_order %>
<%end%>

<script type=text/javascript>
    <%= render :partial => 'shared/ajax_javascripts' %>
    jQuery( "#order_profile_select").change(function() {reload_form(); } );
</script>

app/views/experiment_orders/index.html.erb
<%= content_for :local_navigation do %>
  <%= toolbar_menu_actions(@task).html_safe %>
<% end %>

<%= content_for :title do %>
  <%= @task.element_type.name %>: <%= @task.name %> - <%= t('.title') %>
<% end %>

<%= content_for :breadcrumb do %>
  <% breadcrumb = @task.project_element.self_and_ancestors %>
  <%= breadcrumbs(breadcrumb).html_safe %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th><%= Order.human_attribute_name(:name) %></th>
      <th><%= Order.human_attribute_name(:created_at) %></th>
      <th><%= Order.human_attribute_name(:coast_order_id) %></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.name, order_path(order) %></td>
        <td><%= long_date(order.created_at) %></td>
        <td><%= link_to order.coasts_order_id, order.coasts_order_url %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/experiment_orders/new.html.erb
<%= content_for :title do %>
    <h1><%= t('title.new', :name => Order.name) %> <%= @task.element_type_name %>: <%= @task.name %> </h1>
<% end %>


<%= content_for :breadcrumb do %>
    <%= breadcrumbs(@task.folder.self_and_ancestors).html_safe %>
<% end %>

<div class="portlet">
   <div id='content'>
     <%= render partial: 'order_form' %>
   </div>
</div>

<script type=text/javascript>

    function reload_form() {
        jQuery.ajax({
            url : '<%=renew_form_experiment_orders_path(@task)%>?order_profile_id='+jQuery("#order_profile_select").val(),
            type: 'GET',
            success: function(data){
                jQuery('#content').html(data);
            }
        });
    }

    function switch_internal_external()
    {
        if (jQuery('#order_use_internal_recipient').val()=='true')
        {
            jQuery('#internal').removeAttr('style')
            jQuery('#external').attr('style', 'display: none')
        }
        else
        {
            jQuery('#internal').attr('style', 'display: none')
            jQuery('#external').removeAttr('style')
        }
    }
</script>

<% content_for :ext_on_ready do %>
    jQuery( "#order_profile_select").change(function() {reload_form(); } );
<% end %>

app/views/experiment_orders/renew_form.html.erb
<%= render partial: 'order_form' %>